# Generated by Django 3.2.5 on 2021-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_rename_describution_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='describution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
