# Generated by Django 3.2.5 on 2021-07-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_auto_20210725_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
